### ISSUE TITLE
Sampling Functions

### ISSUE THREAD

**Issue by rossviljoen** [JuliaGaussianProcesses/BayesianLinearRegressors.jl#22]
It might be useful to have an API to draw entire function samples from a BLR by sampling a fixed set of weights. Would there be interest in adding something like this?

**Comment by willtebbutt** [comment]
Yes please -- I mean, I think it would make sense to quite literally implement `rand(::AbstractRNG, ::BLR)` or whatever, because there's pretty much just a single right way to do it.
