### ISSUE TITLE
Use the AbstractVectors convention for inputs instead of matrices

### ISSUE THREAD

**Issue by rossviljoen** [JuliaGaussianProcesses/BayesianLinearRegressors.jl#25]
The package currently assumes (in the readme) that:

> inputs X should be a D x N matrix of Reals where each column is from one data point.

it would be better to adopt the [KernelFunctions convention](https://juliagaussianprocesses.github.io/KernelFunctions.jl/stable/design/#why_abstract_vectors) of using AbstractVectors everywhere

**Comment by willtebbutt** [comment]
So the situation as it stands on this point is
1. a `ColVecs` should work fine.
2. a `RowVecs` will probably fail loudly, but the error message will be fairly useless
3. any other type with a field called `X` will also error loudly, and not particularly helpfully.

I suspect, therefore, that we just need to add some code to convert inputs into `ColVec`s, and to ensure that a decent error message is thrown when an input type that we don't know how to handle is provided.

@rossviljoen are you keen to work on this? If not, I'll probably take a stab at it some time over the next couple of days. Should really be a 10 minute job.

**Comment by rossviljoen** [comment]
You'll probably get to it before me so go for it :smile:
