### ISSUE TITLE
Add function samples section to readme

### ISSUE THREAD

**Issue by rossviljoen** [JuliaGaussianProcesses/BayesianLinearRegressors.jl#31]
Add an example of drawing function samples to the readme.

Alternatively, since the readme is getting pretty big, it might be time for proper docs?

**Comment by willtebbutt** [comment]
> Add an example of drawing function samples to the readme.

Yes please.

> Alternatively, since the readme is getting pretty big, it might be time for proper docs?

I'm not too fussed either way with this.
