### ISSUE TITLE
Parametrizable non-linear feature mapping ϕ

### ISSUE THREAD

**Issue by mvsoom** [JuliaGaussianProcesses/BayesianLinearRegressors.jl#32]
What would be a good approach to do Bayesian regression with **parametrized** basis functions?

As an example of basis functions without extra parameters, here is how I implemented the appropriate kernel `f` for 1D regression using the basis `[1, x, x²]` with your excellent library:
```julia
N = 50 # Number of 1D datapoints on the interval [0, 1]
M = 3 # Number of basis functions

t = collect(range(0, 1, length=N))
X = RowVecs(reshape(t, :, 1)) # (N, D)

function ϕ(X::RowVecs)
	x = only.(X) # Flatten (N, 1) to Vector of length N
	Q = [xₙ^(m-1) for xₙ in x, m in 1:M] # (N,M)
	return RowVecs(Q)
end

Σ = Diagonal(ones(M))
Λ = inv(Σ)
blr = BayesianLinearRegressor(zeros(M), Λ)
f = BasisFunctionRegressor(blr, ϕ)

rand(f(X)) # Sample a function evaluated at t
```
Now I would like to have more complicated basis functions with parameters `θ`. For example, if we do RBF regression with unit lengthscale and at `M` locations ` θ[1], θ[2], ..., θ[M]`, the `ϕ` mapping would look something like this:
```julia
function ϕ(X::RowVecs, θ::Vector)
	x = only.(X) # Flatten (N, 1) to Vector of length N
	Q = [exp(-(xₙ - θ[m])^2/2) for xₙ in x, m in 1:M] # (N,M)
	return RowVecs(Q)
end
```
I want to optimize `θ` as if it was a parameter of the GP `f`, and ideally assign priors, do MCMC, and so forth. What would be a good way to pursue this? I wanted to ask because I quite new to the Julia inference ecosystem. I would appreciate very much any advice. Thank you!

**Comment by willtebbutt** [comment]
Hiya @mvsoom . I would recommend taking a look at the structure of the examples in AbstractGPs.jl. For example [hyperparameter optimisation](https://juliagaussianprocesses.github.io/AbstractGPs.jl/dev/examples/mauna-loa/#Hyperparameter-Optimization), and the approximate inference examples also found in the examples.

In short -- the ecosystem has the tools you need to do this, and we currently leave it up to you to combine them to achieve your goals.

**Comment by mvsoom** [comment]
OK, that looks very good. Thanks for the wonderful package!
