### ISSUE TITLE
Would it make sense to unify BayesianLinearRegressor and BasisFunctionRegressor?

### ISSUE THREAD

**Issue by SebastianCallh** [JuliaGaussianProcesses/BayesianLinearRegressors.jl#37]
Hi! Thank you for this package, it is really nice. 

I was surprised to see feature mappings implemented as a separate wrapper object `BasisFunctionRegressor` since `BayesianLinearRegressor` is just `BasisFunctionRegressor` with `ϕ = identity`. Would it not make sense for `BayesianLinearRegressor ` to take an optional `ϕ` which defaults to `identity` instead? 
There might be efficiency gains or other benefits from this implementation I am not seeing. It would be interesting to hear the motivation behind this implementation!

**Comment by willtebbutt** [comment]
So we introduced the `BasisFunctionRegressor` in [this](https://github.com/JuliaGaussianProcesses/BayesianLinearRegressors.jl/pull/30) PR.

I think I pretty much just stated that I wanted to have it implemented the way that it is without stating why. I think it's really just a matter of taste. I guess I personally just feel that keeps the BLR implementation really clean -- if you just want to do BLR you should not (in my view) have to worry about a feature mapping when you're reading the code.

There aren't any particular performance-related reasons to do it this way.

Is there a particular reason that you're keen to unify the two?

**Comment by SebastianCallh** [comment]
I was thinking it require less code and has a smaller API surface. Having a single struct exposed feels more intuitive to me. I see that the exact same idea was proposed and rejected in the linked PR though (I completely missed the discussion in the PR) which I of course respect.

**Comment by willtebbutt** [comment]
That's fair. I think on balance I'd rather keep it as-is, for the reasons I've mentioned above if that's okay.

Although now looking at the basis-function implementation I think we've got a bug in `posterior` (it returns a BLR, rather than a BFR, which is a problem)... @rossviljoen did you never encounter this when we first implemented the feature?

**Comment by SebastianCallh** [comment]
Yeah that doesn't look correct.  I looks to me like solving it in the current setup requires a new type like `FiniteBFR` to dispatch on, but wouldn't that also require duplicating the interface functions for that type as well? What are your thoughts on solving it? (Of course if there was only one unified implementation we would circumvent the issue entirely ;) )
